### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by CordlessCoder**
Finished the rewrite.
The user can now provide their own themes.
The generation of the LAB version of the image is now parallelized.
It now reuses the original image allocation, only mutating its pixels.
Added support for providing the theme as a JSON string.
Reorganized the CLI.
Added batch processing support.
Added output folder parameter.

### CODE REVIEW

**Comment by CordlessCoder** [comment]
And for performance, this version processes a 4000x4000 image in ~10 seconds, compared to the original's 14.5

**Comment by CordlessCoder** [comment]
added the themes from 0.5

**Comment by doprz** [comment]
Thank you for your contribution and for being the first PR! Here are some of my thoughts:
- Remove the files you added under the `palettes` folder as they are already included in `v0.5.0`
- Nice work with performance and code organization
- There are a couple of typos, however, I'll fix them after merging as I plan on adding new features and cleaning up the code

Once again thank you for your contribution!

**Comment by CordlessCoder** [comment]
I didn't really "add" the files, I just started working before you added them. Should've rebased moment.

**Comment by CordlessCoder** [comment]
Fixed the repeated palette typos. I really need to learn how to spell 💀

**Comment by doprz** [comment]
1. When you edited the files, it updated the GitHub diff view.
2. Thanks for fixing the typos; don't worry about it, it happens.

I will be merging your PR shortly.

**Review by doprz — APPROVED** [review]
Approved

**Pull request merged**
