### PR TITLE
merged LAB conversion and color approximation, removing an allocation.

### PR DESCRIPTION
**Pull request by CordlessCoder**
I also added a pre-processing step to the palettes being used right before they're converted to LAB: It now runs a deduplication step, which has a large performance improvement whenever multiple styles of the same theme are used at the same time.

### CODE REVIEW

**Comment by CordlessCoder** [comment]
Added the new themes to the CLI help message

**Comment by CordlessCoder** [comment]
Also fixed the unstable feature. Tested and compiles on Rust 1.69.0 stable

**Comment by doprz** [comment]
Thank you, I was working on the duplication issue as some themes like `edge` have a lot of duplicate values.
I'm also rewriting some sections of code so I will push shortly which will hopefully not interfere that much with your PR.

Also, I think it might be a good idea to create feature issues so that they're tracked and can be marked into milestones as I'm almost ready to release `v1.0.0-rc`.

**Comment by doprz** [comment]
Before merging, please go over your PR as the changes that I made in PR #5 may conflict with yours + I refactored large parts of the code. Thanks.

**Comment by CordlessCoder** [comment]
I already went over #5 as well as fixing the conflicts. The changes are great

**Comment by doprz** [comment]
Ok, I will take a second look at your PR before merging. Great job with these improvements.

**Comment by doprz** [comment]
Approved!

**Pull request merged**
